/**
 * @file MtcAcv.java
 * @brief MtcAcv interface
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

/**
 * @brief MtcAcv interface
 */
public class MtcAcv {
/** 
 * @brief MTC archive logs and commit to server.
 *
 * @param [in] pcRoot The root directory.
 * @param [in] pcDir The log diretory.
 * @param [in] pcAcvName The archived file name.
 * @param [in] pcMemo The memo.
 * @param [in] pcDeviceId The device id.
 *
 */
  public static void Mtc_AcvCommit(String pcRoot, String pcDir, String pcAcvName, String pcMemo, String pcDeviceId) {
    MtcAcvJNI.Mtc_AcvCommit(pcRoot, pcDir, pcAcvName, pcMemo, pcDeviceId);
  }

/** 
 * @brief MTC archive logs and commit to server.
 *
 * @param [in] pcRoot The root directory.
 * @param [in] ppcDirs The log diretories.
 * @param [in] pcAcvName The archived file name.
 * @param [in] pcMemo The memo.
 * @param [in] pcDeviceId The device id.
 *
 */
  public static void Mtc_AcvCommitX(String pcRoot, MtcString ppcDirs, String pcAcvName, String pcMemo, String pcDeviceId) {
    MtcAcvJNI.Mtc_AcvCommitX(pcRoot, ppcDirs, pcAcvName, pcMemo, pcDeviceId);
  }

}
