/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

public class MtcCliCfgJNI {
  public final static native void MtcNumber_value_set(long jarg1, MtcNumber jarg1_, int jarg2);
  public final static native int MtcNumber_value_get(long jarg1, MtcNumber jarg1_);
  public final static native long new_MtcNumber();
  public final static native void delete_MtcNumber(long jarg1);
  public final static native void MtcByteArray_data_set(long jarg1, MtcByteArray jarg1_, long jarg2);
  public final static native long MtcByteArray_data_get(long jarg1, MtcByteArray jarg1_);
  public final static native void MtcByteArray_size_set(long jarg1, MtcByteArray jarg1_, long jarg2);
  public final static native long MtcByteArray_size_get(long jarg1, MtcByteArray jarg1_);
  public final static native void MtcByteArray_value_set(long jarg1, MtcByteArray jarg1_, byte[] jarg2);
  public final static native byte[] MtcByteArray_value_get(long jarg1, MtcByteArray jarg1_);
  public final static native long new_MtcByteArray();
  public final static native void delete_MtcByteArray(long jarg1);
  public final static native void MtcString_value_set(long jarg1, MtcString jarg1_, String jarg2);
  public final static native String MtcString_value_get(long jarg1, MtcString jarg1_);
  public final static native long new_MtcString();
  public final static native void delete_MtcString(long jarg1);
  public final static native void Mtc_CliCfgSetLogLevel(int jarg1);
  public final static native void Mtc_CliCfgSetLogLevelX(int jarg1);
  public final static native int Mtc_CliCfgSetLogPrint(boolean jarg1);
  public final static native boolean Mtc_CliCfgGetUseDetLclIp();
  public final static native int Mtc_CliCfgSetUseDetLclIp(boolean jarg1);
  public final static native boolean Mtc_CliCfgGetSuptNetDetect();
  public final static native int Mtc_CliCfgSetSuptNetDetect(boolean jarg1);
  public final static native boolean Mtc_CliCfgGetSuptEncPwd();
  public final static native int Mtc_CliCfgSetSuptEncPwd(boolean jarg1);
  public final static native int Mtc_CliCfgGetRegCap();
  public final static native int Mtc_CliCfgSetRegCap(int jarg1);
  public final static native int Mtc_CliCfgClrRegCap(int jarg1);
  public final static native int Mtc_CliCfgGetCmccExtRegCap();
  public final static native int Mtc_CliCfgSetCmccExtRegCap(int jarg1);
  public final static native int Mtc_CliCfgClrCmccExtRegCap(int jarg1);
  public final static native int Mtc_CliCfgSetLogDir(String jarg1);
  public final static native String Mtc_CliCfgGetLogDir();
  public final static native int Mtc_CliCfgSetLoginLogDir(String jarg1);
  public final static native String Mtc_CliCfgGetLoginLogDir();
  public final static native int Mtc_CliCfgSetLicenseFileName(String jarg1);
  public final static native int Mtc_CliCfgSetAesKey(String jarg1);
  public final static native int Mtc_CliCfgSetContext(Object jarg1);
  public final static native boolean Mtc_CliCfgGetFileEncrypt();
  public final static native int Mtc_CliCfgSetFileEncrypt(boolean jarg1);
  public final static native int Mtc_CliCfgGetRegSrvType();
  public final static native int Mtc_CliCfgSetRegSrvType(int jarg1);
  public final static native int Mtc_CliCfgGetTmrLenWaitReg();
  public final static native int Mtc_CliCfgSetTmrLenWaitReg(int jarg1);
  public final static native boolean Mtc_CliCfgGetSuptRefreshBefExpr();
  public final static native int Mtc_CliCfgSetSuptRefreshBefExpr(boolean jarg1);
  public final static native int Mtc_CliCfgSetChkDevIdType(int jarg1);
  public final static native boolean Mtc_CliCfgGetTimerSelfDrvEnable();
  public final static native int Mtc_CliCfgSetTimerSelfDrvEnable(boolean jarg1);
  public final static native boolean Mtc_CliCfgGetLogcatPrint();
  public final static native int Mtc_CliCfgSetLogcatPrint(boolean jarg1);
  public final static native boolean Mtc_CliCfgGetSocketReuseEnable();
  public final static native int Mtc_CliCfgSetSocketReuseEnable(boolean jarg1);
  public final static native boolean Mtc_CliCfgGetUdpConnectEnable();
  public final static native int Mtc_CliCfgSetUdpConnectEnable(boolean jarg1);
}
