/**
 * @file MtcDoodleConstants.java
 * @brief MtcDoodleConstants constants
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

/**
 * @brief MtcDoodleConstants constants
 */
public interface MtcDoodleConstants {
  public final static String MtcDoodleImageTypeKey = "MtcDoodleImageTypeKey";
  public final static String MtcDoodleImageNameKey = "MtcDoodleImageNameKey";
  public final static String MtcDoodleImageUriKey = "MtcDoodleImageUriKey";
  public final static String MtcDoodleResolutionKey = "MtcDoodleResolutionKey";
  public final static String MtcDoodlePositionKey = "MtcDoodlePositionKey";
  public final static String MtcDoodleActionTypeKey = "MtcDoodleActionTypeKey";
  public final static String MtcDoodleSeqNoKey = "MtcDoodleSeqNoKey";
  public final static String MtcDoodleBrushKey = "MtcDoodleBrushKey";
  public final static String MtcDoodleWidthKey = "MtcDoodleWidthKey";
  public final static String MtcDoodleColorKey = "MtcDoodleColorKey";
  public final static String MtcDoodlePageIdKey = "MtcDoodlePageIdKey";
  public final static String MtcDoodlePageCountKey = "MtcDoodlePageCountKey";
  public final static String MtcDoodleUserUriKey = "MtcDoodleUserUriKey";
  public final static String MtcDoodleContentKey = "MtcDoodleContentKey";
  // EN_MTC_DOODLE_IMAGE_TYPE 
  public final static int EN_MTC_DOODLE_IMAGE_PNG = 1;
  public final static int EN_MTC_DOODLE_IMAGE_JPEG = EN_MTC_DOODLE_IMAGE_PNG + 1;
  public final static int EN_MTC_DOODLE_IMAGE_BMP = EN_MTC_DOODLE_IMAGE_JPEG + 1;

  // EN_MTC_DOODLE_ACTION_TYPE 
  public final static int EN_MTC_DOODLE_ACTION_DRAW = 0;
  public final static int EN_MTC_DOODLE_ACTION_ERASE = EN_MTC_DOODLE_ACTION_DRAW + 1;
  public final static int EN_MTC_DOODLE_ACTION_CLEAN = EN_MTC_DOODLE_ACTION_ERASE + 1;
  public final static int EN_MTC_DOODLE_ACTION_UNDO = EN_MTC_DOODLE_ACTION_CLEAN + 1;
  public final static int EN_MTC_DOODLE_ACTION_SELECT_PAGE = EN_MTC_DOODLE_ACTION_UNDO + 1;
  public final static int EN_MTC_DOODLE_ACTION_START = EN_MTC_DOODLE_ACTION_SELECT_PAGE + 1;
  public final static int EN_MTC_DOODLE_ACTION_STOP = EN_MTC_DOODLE_ACTION_START + 1;
  public final static int EN_MTC_DOODLE_ACTION_LASER_POINT = EN_MTC_DOODLE_ACTION_STOP + 1;
  public final static int EN_MTC_DOODLE_ACTION_ARROW = EN_MTC_DOODLE_ACTION_LASER_POINT + 1;
  public final static int EN_MTC_DOODLE_ACTION_DRAW_RECTANGLE = EN_MTC_DOODLE_ACTION_ARROW + 1;
  public final static int EN_MTC_DOODLE_ACTION_DRAW_ELLIPSE = EN_MTC_DOODLE_ACTION_DRAW_RECTANGLE + 1;
  public final static int EN_MTC_DOODLE_ACTION_TEXT = EN_MTC_DOODLE_ACTION_DRAW_ELLIPSE + 1;

}
