/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

public class MtcGsDbJNI {
  public final static native void MtcNumber_value_set(long jarg1, MtcNumber jarg1_, int jarg2);
  public final static native int MtcNumber_value_get(long jarg1, MtcNumber jarg1_);
  public final static native long new_MtcNumber();
  public final static native void delete_MtcNumber(long jarg1);
  public final static native void MtcByteArray_data_set(long jarg1, MtcByteArray jarg1_, long jarg2);
  public final static native long MtcByteArray_data_get(long jarg1, MtcByteArray jarg1_);
  public final static native void MtcByteArray_size_set(long jarg1, MtcByteArray jarg1_, long jarg2);
  public final static native long MtcByteArray_size_get(long jarg1, MtcByteArray jarg1_);
  public final static native void MtcByteArray_value_set(long jarg1, MtcByteArray jarg1_, byte[] jarg2);
  public final static native byte[] MtcByteArray_value_get(long jarg1, MtcByteArray jarg1_);
  public final static native long new_MtcByteArray();
  public final static native void delete_MtcByteArray(long jarg1);
  public final static native void MtcString_value_set(long jarg1, MtcString jarg1_, String jarg2);
  public final static native String MtcString_value_get(long jarg1, MtcString jarg1_);
  public final static native long new_MtcString();
  public final static native void delete_MtcString(long jarg1);
  public final static native boolean Mtc_GsDbGetPushEnable();
  public final static native int Mtc_GsDbGetPullType();
  public final static native boolean Mtc_GsDbGetPullOpen();
  public final static native int Mtc_GsDbGetLocInfoMaxValidTime();
  public final static native int Mtc_GsDbGetBlockTimer();
  public final static native int Mtc_GsDbGetTxtMaxLen();
  public final static native String Mtc_GsDbGetOneApiHost();
  public final static native short Mtc_GsDbGetOneApiPort();
  public final static native String Mtc_GsDbGetOneApiRoot();
  public final static native String Mtc_GsDbGetOneApiVers();
  public final static native String Mtc_GsDbGetHslpAddr();
  public final static native String Mtc_GsDbGetHslpAddrType();
  public final static native int Mtc_GsDbGetMediaProtoType();
  public final static native int Mtc_GsDbSetPushEnable(boolean jarg1);
  public final static native int Mtc_GsDbSetPullType(int jarg1);
  public final static native int Mtc_GsDbSetPullOpen(boolean jarg1);
  public final static native int Mtc_GsDbSetBlockTimer(int jarg1);
  public final static native int Mtc_GsDbSetOneApiHost(String jarg1);
  public final static native int Mtc_GsDbSetOneApiPort(short jarg1);
  public final static native int Mtc_GsDbSetOneApiRoot(String jarg1);
  public final static native int Mtc_GsDbSetOneApiVers(String jarg1);
  public final static native int Mtc_GsDbSetMediaProtoType(int jarg1);
  public final static native int Mtc_GsDbSetAllowedSmsType(int jarg1);
  public final static native int Mtc_GsDbGetAllowedSmsType();
}
