/**
 * @file MtcImOmsg.java
 * @brief MtcImOmsg interface
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

/**
 * @brief MtcImOmsg interface
 */
public class MtcImOmsg implements MtcImOmsgConstants {
/**
 * @brief MTC Get Offline Message list Message Count.
 *
 * @param [in] iMsgLstId The offline-message list id.
 *
 * @retval The Message Count.
 */
  public static int Mtc_ImOMsgGetMsgCount(int iMsgLstId) {
    return MtcImOmsgJNI.Mtc_ImOMsgGetMsgCount(iMsgLstId);
  }

/**
 * @brief MTC Get Offline Message Type By Index.
 *
 * @param [in] iMsgLstId The offline-message list id.
 * @param [in] iIndex The Index.
 *
 * @retval The Message Type.
 */
  public static int Mtc_ImOMsgGetMsgTypeByIndex(int iMsgLstId, int iIndex) {
    return MtcImOmsgJNI.Mtc_ImOMsgGetMsgTypeByIndex(iMsgLstId, iIndex);
  }

/**
 * @brief MTC Get Offline Message MessageId By Index.
 *
 * @param [in] iMsgLstId The offline-message list id.
 * @param [in] iIndex The Index.
 *
 * @retval The Message Id.
 */
  public static int Mtc_ImOMsgGetMsgIdByIndex(int iMsgLstId, int iIndex) {
    return MtcImOmsgJNI.Mtc_ImOMsgGetMsgIdByIndex(iMsgLstId, iIndex);
  }

/**
 * @brief MTC Get Offline Message SessionId By Index.
 *
 * @param [in] iMsgLstId The offline-message list id.
 * @param [in] iIndex The Index.
 *
 * @retval The Session Id.
 */
  public static int Mtc_ImOMsgGetSessIdByIndex(int iMsgLstId, int iIndex) {
    return MtcImOmsgJNI.Mtc_ImOMsgGetSessIdByIndex(iMsgLstId, iIndex);
  }

}
