/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

public interface MtcImConfConstants {
  // EN_MTC_CONFM_STATE_TYPE 
  public final static int EN_MTC_CONFM_STATE_IDLE = 0;
  public final static int EN_MTC_CONFM_STATE_ACTIVE = EN_MTC_CONFM_STATE_IDLE + 1;

}
