/**
 * @file MtcImConf.java
 * @brief MtcImConf interface
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

/**
 * @brief MtcImConf interface
 */
public class MtcImConf implements MtcImConfConstants {
/**
 * @brief MTC Subscribe conference list.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref mtcImCbConfSubsLstOk or @ref mtcImCbConfSubsLstFailed.
 *
 * @param [in] iGrpType Type of subscribe, @ref MtcImSessConstants::EN_MTC_IM_SESS_GRP_TYPE_ALL.
 * @retval MtcCommonConstants::ZOK Start to subscribe conference list successfully.
 * @retval MtcCommonConstants::ZFAILED Subscribe conference list failed.
 */
  public static int Mtc_ImConfMSubsConfLst(int iGrpType) {
    return MtcImConfJNI.Mtc_ImConfMSubsConfLst(iGrpType);
  }

/**
 * @brief MTC Subscribe conference info.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref mtcImCbConfSubsInfoOk or @ref mtcImCbConfSubsInfoFailed.
 *
 * @param [in] pcGroupId The group session identity.
 *
 * @return conference id successfully or ZMAXUINT failed.
 */
  public static int Mtc_ImConfMSubsConf(String pcGroupId) {
    return MtcImConfJNI.Mtc_ImConfMSubsConf(pcGroupId);
  }

/**
 * @brief MTC Get conference group size.
 *
 * @return conference group size.
 */
  public static int Mtc_ImConfMGetConfGrpSize() {
    return MtcImConfJNI.Mtc_ImConfMGetConfGrpSize();
  }

/**
 * @brief MTC Get conference group id by index.
 *
 * @param [in] iIndex The group index.
 *
 * @return conference group id successfully or ZMAXUINT failed.
 */
  public static int Mtc_ImConfMGetConfGrpId(int iIndex) {
    return MtcImConfJNI.Mtc_ImConfMGetConfGrpId(iIndex);
  }

/**
 * @brief MTC Get conference group session identity.
 *
 * @param [in] iGrpId The group id.
 *
 * @return conference group session identity.
 */
  public static String Mtc_ImConfMGetConfGrpSessId(int iGrpId) {
    return MtcImConfJNI.Mtc_ImConfMGetConfGrpSessId(iGrpId);
  }

/**
 * @brief MTC Get conference conversation id.
 *
 * @param [in] iGrpId The group id.
 *
 * @return conference conversation id.
 */
  public static String Mtc_ImConfMGetConfConvId(int iGrpId) {
    return MtcImConfJNI.Mtc_ImConfMGetConfConvId(iGrpId);
  }

/**
 * @brief MTC Get conference name.
 *
 * @param [in] iGrpId The group id.
 *
 * @return conference name.
 */
  public static String Mtc_ImConfMGetConfName(int iGrpId) {
    return MtcImConfJNI.Mtc_ImConfMGetConfName(iGrpId);
  }

/**
 * @brief MTC Get conference group type.
 *
 * @param [in] iGrpId The group id.
 *
 * @return conference group type @ref MtcImSessConstants::EN_MTC_IM_SESS_GRP_TYPE_ALL.
 */
  public static int Mtc_ImConfMGetConfGrpType(int iGrpId) {
    return MtcImConfJNI.Mtc_ImConfMGetConfGrpType(iGrpId);
  }

/**
 * @brief MTC Get conference active.
 *
 * @param [in] iConfId The conference id.
 *
 * @return conference active.
 */
  public static boolean Mtc_ImConfGetActive(int iConfId) {
    return MtcImConfJNI.Mtc_ImConfGetActive(iConfId);
  }

/**
 * @brief MTC Get conference locked.
 *
 * @param [in] iConfId The conference id.
 *
 * @return conference locked.
 */
  public static boolean Mtc_ImConfGetLocked(int iConfId) {
    return MtcImConfJNI.Mtc_ImConfGetLocked(iConfId);
  }

/**
 * @brief MTC Get conference offlinesm.
 *
 * @param [in] iConfId The conference id.
 *
 * @return conference offlinesm.
 */
  public static int Mtc_ImConfGetOfflineSm(int iConfId) {
    return MtcImConfJNI.Mtc_ImConfGetOfflineSm(iConfId);
  }

/**
 * @brief MTC Get conference max user count.
 *
 * @param [in] iConfId The conference id.
 *
 * @return conference max user count.
 */
  public static int Mtc_ImConfGetMaxUsrCnt(int iConfId) {
    return MtcImConfJNI.Mtc_ImConfGetMaxUsrCnt(iConfId);
  }

/**
 * @brief MTC Get conference user count.
 *
 * @param [in] iConfId The conference id.
 *
 * @return conference user count.
 */
  public static int Mtc_ImConfGetUsrCnt(int iConfId) {
    return MtcImConfJNI.Mtc_ImConfGetUsrCnt(iConfId);
  }

/**
 * @brief MTC Get conference subject.
 *
 * @param [in] iConfId The conference id.
 *
 * @return conference subject.
 */
  public static String Mtc_ImConfGetSubject(int iConfId) {
    return MtcImConfJNI.Mtc_ImConfGetSubject(iConfId);
  }

/**
 * @brief MTC Get conference display name.
 *
 * @param [in] iConfId The conference id.
 *
 * @return conference display name.
 */
  public static String Mtc_ImConfGetDispName(int iConfId) {
    return MtcImConfJNI.Mtc_ImConfGetDispName(iConfId);
  }

/**
 * @brief MTC Get conference group session identity.
 *
 * @param [in] iConfId The conference id.
 *
 * @return conference group session identity.
 */
  public static String Mtc_ImConfGetGrpSessId(int iConfId) {
    return MtcImConfJNI.Mtc_ImConfGetGrpSessId(iConfId);
  }

/**
 * @brief MTC Get conference participant list id.
 *
 * @param [in] iConfId The conference id.
 *
 * @return conference participant list id.
 */
  public static int Mtc_ImConfGetPartpLstId(int iConfId) {
    return MtcImConfJNI.Mtc_ImConfGetPartpLstId(iConfId);
  }

/**
 * @brief MTC Get conference version id.
 *
 * @param [in] iConfId The conference id.
 *
 * @return conference version id.
 */
  public static int Mtc_ImConfGetVertionId(int iConfId) {
    return MtcImConfJNI.Mtc_ImConfGetVertionId(iConfId);
  }

}
