/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

public class MtcMediaJNI {
  public final static native void MtcNumber_value_set(long jarg1, MtcNumber jarg1_, int jarg2);
  public final static native int MtcNumber_value_get(long jarg1, MtcNumber jarg1_);
  public final static native long new_MtcNumber();
  public final static native void delete_MtcNumber(long jarg1);
  public final static native void MtcByteArray_data_set(long jarg1, MtcByteArray jarg1_, long jarg2);
  public final static native long MtcByteArray_data_get(long jarg1, MtcByteArray jarg1_);
  public final static native void MtcByteArray_size_set(long jarg1, MtcByteArray jarg1_, long jarg2);
  public final static native long MtcByteArray_size_get(long jarg1, MtcByteArray jarg1_);
  public final static native void MtcByteArray_value_set(long jarg1, MtcByteArray jarg1_, byte[] jarg2);
  public final static native byte[] MtcByteArray_value_get(long jarg1, MtcByteArray jarg1_);
  public final static native long new_MtcByteArray();
  public final static native void delete_MtcByteArray(long jarg1);
  public final static native void MtcString_value_set(long jarg1, MtcString jarg1_, String jarg2);
  public final static native String MtcString_value_get(long jarg1, MtcString jarg1_);
  public final static native long new_MtcString();
  public final static native void delete_MtcString(long jarg1);
  public final static native void ST_MTC_RECT_iX_set(long jarg1, ST_MTC_RECT jarg1_, int jarg2);
  public final static native int ST_MTC_RECT_iX_get(long jarg1, ST_MTC_RECT jarg1_);
  public final static native void ST_MTC_RECT_iY_set(long jarg1, ST_MTC_RECT jarg1_, int jarg2);
  public final static native int ST_MTC_RECT_iY_get(long jarg1, ST_MTC_RECT jarg1_);
  public final static native void ST_MTC_RECT_iWidth_set(long jarg1, ST_MTC_RECT jarg1_, int jarg2);
  public final static native int ST_MTC_RECT_iWidth_get(long jarg1, ST_MTC_RECT jarg1_);
  public final static native void ST_MTC_RECT_iHeight_set(long jarg1, ST_MTC_RECT jarg1_, int jarg2);
  public final static native int ST_MTC_RECT_iHeight_get(long jarg1, ST_MTC_RECT jarg1_);
  public final static native long new_ST_MTC_RECT();
  public final static native void delete_ST_MTC_RECT(long jarg1);
  public final static native int Mtc_MdmAnSetSendBitrateMode(int jarg1);
  public final static native int Mtc_MdmAnSetBitrateMode(int jarg1);
  public final static native int Mtc_MdmAnGetBitrateMode();
  public final static native int Mtc_MdmAnSetResolution(int jarg1, int jarg2);
  public final static native int Mtc_MdmAnGetMaxVol();
  public final static native float Mtc_MdmGetScore();
  public final static native int Mtc_MediaFileWavToAmr(String jarg1, String jarg2);
  public final static native int Mtc_MediaFileAmrToWav(String jarg1, String jarg2);
  public final static native int Mtc_MdmGetAndroidAudioMode();
  public final static native String Mtc_MdmGetAndroidAudioInputDevice();
  public final static native String Mtc_MdmGetAndroidAudioOutputDevice();
  public final static native int Mtc_MdmGetCaptureParms(MtcNumber jarg1, MtcNumber jarg2, MtcNumber jarg3);
  public final static native boolean Mtc_MdmGetOsAec();
  public final static native boolean Mtc_MdmGetOsAgc();
}
