/**
 * @file MtcPa.java
 * @brief MtcPa interface
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

/**
 * @brief MtcPa interface
 */
public class MtcPa implements MtcPaConstants {
/**
 * @brief The public account add subscribe.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref Mtc_PaCbSetPaAddSubsOk or @ref Mtc_PaCbSetPaAddSubsFailed.
 *
 * @param [in] pcPaUuid The pa uuid.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessAddSubs(String pcPaUuid) {
    return MtcPaJNI.Mtc_PaSessAddSubs(pcPaUuid);
  }

/**
 * @brief The public account cancle subscribe.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref Mtc_PaCbSetPaCancelSubsOk or @ref Mtc_PaCbSetPaCancelSubsFailed.
 *
 * @param [in] pcPaUuid The pa uuid.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessCancelSubs(String pcPaUuid) {
    return MtcPaJNI.Mtc_PaSessCancelSubs(pcPaUuid);
  }

/**
 * @brief The public accounts query user subscribed.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref Mtc_PaCbSetPaQryUsrSubsOk or @ref Mtc_PaCbSetPaQryUsrSubsFailed.
 *
 * @param [in] iOrder The public account list sorting strategy, 
 *             value 0 indicates order by subscribed time desc, 
 *             value 1 indicates ordey by name.
 * @param [in] iPageSize The public account id number each page.
 * @param [in] iPageNum The public account list pagination.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessQryUsrSubs(int iOrder, int iPageSize, int iPageNum) {
    return MtcPaJNI.Mtc_PaSessQryUsrSubs(iOrder, iPageSize, iPageNum);
  }

/**
 * @brief The public account get public list.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref Mtc_PaCbSetPaGetPubLstOk or @ref Mtc_PaCbSetPaGetPubLstFailed.
 *
 * @param [in] pcKeyword The public account search keyword.
 * @param [in] iOrder The public account list sorting strategy.
 *             value 0 indicates order by subscribed time desc, 
 *             value 1 indicates ordey by name.
 * @param [in] iPageSize The public account id number each page.
 * @param [in] iPageNum The public account list pagination.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessGetPubLst(String pcKeyword, int iOrder, int iPageSize, int iPageNum) {
    return MtcPaJNI.Mtc_PaSessGetPubLst(pcKeyword, iOrder, iPageSize, iPageNum);
  }

/**
 * @brief The public account get public list recommend.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref Mtc_PaCbSetPaGetPubLstRecmdOk or @ref Mtc_PaCbSetPaGetPubLstRecmdFailed.
 *
 * @param [in] iType The public source type, @see @ref MtcPaConstants::EN_MTC_PA_UNKNOWN.
 * @param [in] iPageSize The public account id number each page.
 * @param [in] iPageNum The public account list pagination.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessGetPubLstRecmd(int iType, int iPageSize, int iPageNum) {
    return MtcPaJNI.Mtc_PaSessGetPubLstRecmd(iType, iPageSize, iPageNum);
  }

/**
 * @brief The public account get public detail.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref Mtc_PaCbSetPaGetPubDetailOk or @ref Mtc_PaCbSetPaGetPubDetailFailed.
 *
 * @param [in] pcPaUuid The public account unique id.
 * @param [in] zUpdTime The public account detail last update time.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessGetPubDetail(String pcPaUuid, int zUpdTime) {
    return MtcPaJNI.Mtc_PaSessGetPubDetail(pcPaUuid, zUpdTime);
  }

/**
 * @brief The public account get public menu.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref Mtc_PaCbSetPaGetPubMenuOk or @ref Mtc_PaCbSetPaGetPubMenuFailed.
 *
 * @param [in] pcPaUuid The public account unique id.
 * @param [in] zTimestamp The public account menu last update time.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessGetPubMenu(String pcPaUuid, int zTimestamp) {
    return MtcPaJNI.Mtc_PaSessGetPubMenu(pcPaUuid, zTimestamp);
  }

/**
 * @brief The public accounts get previous message.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref Mtc_PaCbSetPaGetPrevMsgOk or @ref Mtc_PaCbSetPaGetPrevMsgFailed.
 *
 * @param [in] pcPaUuid The public account unique id.
 * @param [in] zTimestamp The public account query message start time.
 * @param [in] iOrder The public account query message time direction.
 * @param [in] iPageSize The public account id number each page.
 * @param [in] iPageNum The public account query message number.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessGetPrevMsg(String pcPaUuid, int zTimestamp, int iOrder, int iPageSize, int iPageNum) {
    return MtcPaJNI.Mtc_PaSessGetPrevMsg(pcPaUuid, zTimestamp, iOrder, iPageSize, iPageNum);
  }

/**
 * @brief The public accounts complain public.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref Mtc_PaCbSetPaComplainPubOk or @ref Mtc_PaCbSetPaComplainPubFailed.
 *
 * @param [in] pcPaUuid The public account unique id.
 * @param [in] iType The public account complain type,
 *             value 1 indicates complain public account,
 *             value 2 indicates complain public message.
 * @param [in] pcReason The public account complain reason.
 * @param [in] pcData The public message data, mandatory if iType euqal 2.
 * @param [in] pcDesc The public account behavior description, option.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessComplainPub(String pcPaUuid, int iType, String pcReason, String pcData, String pcDesc) {
    return MtcPaJNI.Mtc_PaSessComplainPub(pcPaUuid, iType, pcReason, pcData, pcDesc);
  }

/**
 * @brief The public accounts set accept status.
 * 
 * The result will be notified by callbacks which were set by 
 * @ref Mtc_PaCbSetPaComplainPubOk or @ref Mtc_PaCbSetPaComplainPubFailed.
 *
 * @param [in] pcPaUuid The public account unique id.
 * @param [in] pcReason The public account complain reason.
 * @param [in] pcDesc The public account behavior description.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessSetAcptStat(String pcPaUuid, boolean bAcptStat) {
    return MtcPaJNI.Mtc_PaSessSetAcptStat(pcPaUuid, bAcptStat);
  }

/**
 * @brief The public accounts format text to xml message.
 * 
 * @param [in] pcText The text message.
 *
 * @return The xml message.
 */
  public static String Mtc_PaSessEncodeMsg(String pcText) {
    return MtcPaJNI.Mtc_PaSessEncodeMsg(pcText);
  }

/**
 * @brief The public accounts decode public account xml message.
 * 
 * @param [in] pcMsg The public account xml message.
 *
 * @return The public account session id when successfully, otherwise return ZMAXUINT.
 *  When used completely, caller must release session, @see @ref MtcPa::Mtc_PaSessRelease.
 */
  public static int Mtc_PaSessDecodeMsg(String pcXmlMsg) {
    return MtcPaJNI.Mtc_PaSessDecodeMsg(pcXmlMsg);
  }

/**
 * @brief The public accounts session release.
 *
 * @param [in] iSessId The session id.
 */
  public static void Mtc_PaSessRelease(int iSessId) {
    MtcPaJNI.Mtc_PaSessRelease(iSessId);
  }

/**
 * @brief The public accounts get xml message.
 *
 * @param [in] iSessId The session id.
 *
 * @return The xml message.
 */
  public static String Mtc_PaSessGetXmlMsg(int iSessId) {
    return MtcPaJNI.Mtc_PaSessGetXmlMsg(iSessId);
  }

/**
 * @brief The public accounts get pa size.
 *
 * @param [in] iSessId The session id.
 *
 * @return The pa size.
 */
  public static int Mtc_PaSessGetPaSize(int iSessId) {
    return MtcPaJNI.Mtc_PaSessGetPaSize(iSessId);
  }

/**
 * @brief The public accounts get pa size.
 *
 * @param [in] iSessId The session id.
 * @param [in] iIndex The pa index.
 *
 * @return The pa id successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessGetPaId(int iSessId, int iIndex) {
    return MtcPaJNI.Mtc_PaSessGetPaId(iSessId, iIndex);
  }

/**
 * @brief Get public account the menu size.
 *
 * @param [in] iSessId The session id.
 *
 * @return The menu size.
 */
  public static int Mtc_PaSessGetMenuSize(int iSessId) {
    return MtcPaJNI.Mtc_PaSessGetMenuSize(iSessId);
  }

/**
 * @brief Get public account menu id.
 *
 * @param [in] iSessId The session id.
 * @param [in] iIndex The menu index.
 *
 * @return The menu id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessGetMenuId(int iSessId, int iIndex) {
    return MtcPaJNI.Mtc_PaSessGetMenuId(iSessId, iIndex);
  }

/**
 * @brief Get public account the message size.
 *
 * @param [in] iSessId The session id.
 *
 * @return The message size.
 */
  public static int Mtc_PaSessGetMsgSize(int iSessId) {
    return MtcPaJNI.Mtc_PaSessGetMsgSize(iSessId);
  }

/**
 * @brief Get public account message id.
 *
 * @param [in] iSessId The session id.
 * @param [in] iIndex The message index.
 *
 * @return The message id when successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaSessGetMsgId(int iSessId, int iIndex) {
    return MtcPaJNI.Mtc_PaSessGetMsgId(iSessId, iIndex);
  }

/**
 * @brief Get public account session result.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account session result.
 */
  public static String Mtc_PaSessGetResult(int iSessId) {
    return MtcPaJNI.Mtc_PaSessGetResult(iSessId);
  }

/**
 * @brief Get public account session pa uuid.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account uuid.
 */
  public static String Mtc_PaSessGetPaUuid(int iSessId) {
    return MtcPaJNI.Mtc_PaSessGetPaUuid(iSessId);
  }

/**
 * @brief Check public account session has data.
 *
 * @param [in] iSessId The session id.
 *
 * @return The has data flag.
 */
  public static boolean Mtc_PaSessHasData(int iSessId) {
    return MtcPaJNI.Mtc_PaSessHasData(iSessId);
  }

/**
 * @brief Get public account uuid.
 *
 * @param [in] iPaId The public account id.
 *
 * @return The public account unique id.
 */
  public static String Mtc_PaBscGetPaUuid(int iPaId) {
    return MtcPaJNI.Mtc_PaBscGetPaUuid(iPaId);
  }

/**
 * @brief Get public account name.
 *
 * @param [in] iPaId The public account id.
 *
 * @return The public account name.
 */
  public static String Mtc_PaBscGetName(int iPaId) {
    return MtcPaJNI.Mtc_PaBscGetName(iPaId);
  }

/**
 * @brief Get public account recommend level.
 *
 * @param [in] iPaId The public account id.
 *
 * @return The public account recommend level, @see @ref MtcPaConstants::EN_MTC_PA_RECMD_LV_UNKNOWN.
 */
  public static int Mtc_PaBscGetRecmdLv(int iPaId) {
    return MtcPaJNI.Mtc_PaBscGetRecmdLv(iPaId);
  }

/**
 * @brief Get public account logo url.
 *
 * @param [in] iPaId The public account id.
 *
 * @return The public account logo url.
 */
  public static String Mtc_PaBscGetLogoUrl(int iPaId) {
    return MtcPaJNI.Mtc_PaBscGetLogoUrl(iPaId);
  }

/**
 * @brief Get public account introduce.
 *
 * @param [in] iPaId The public account id.
 *
 * @return The public account introduce.
 */
  public static String Mtc_PaBscGetIntro(int iPaId) {
    return MtcPaJNI.Mtc_PaBscGetIntro(iPaId);
  }

/**
 * @brief Get public account id type.
 *
 * @param [in] iPaId The public account id.
 *
 * @return The public account id type.
 */
  public static int Mtc_PaBscGetIdType(int iPaId) {
    return MtcPaJNI.Mtc_PaBscGetIdType(iPaId);
  }

/**
 * @brief Get public account subscribe status.
 *
 * @param [in] iPaId The public account id.
 *
 * @return 1 when public account have subscribed, otherwise return 0.
 */
  public static int Mtc_PaBscGetSubsStat(int iPaId) {
    return MtcPaJNI.Mtc_PaBscGetSubsStat(iPaId);
  }

/**
 * @brief Get public account uuid.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account unique id.
 */
  public static String Mtc_PaDetailGetPaUuid(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetPaUuid(iSessId);
  }

/**
 * @brief Get public account name.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account name.
 */
  public static String Mtc_PaDetailGetName(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetName(iSessId);
  }

/**
 * @brief Get public account authentication company.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account authentication company.
 */
  public static String Mtc_PaDetailGetCompany(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetCompany(iSessId);
  }

/**
 * @brief Get public account introduce.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account introduce.
 */
  public static String Mtc_PaDetailGetIntro(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetIntro(iSessId);
  }

/**
 * @brief Get public account the last information update time.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account update time.
 */
  public static int Mtc_PaDetailGetUpdTime(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetUpdTime(iSessId);
  }

/**
 * @brief Get public account the menu timestamp.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account menu timestamp.
 */
  public static int Mtc_PaDetailGetMenuTimestamp(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetMenuTimestamp(iSessId);
  }

/**
 * @brief Get public account type.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account type.
 */
  public static String Mtc_PaDetailGetType(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetType(iSessId);
  }

/**
 * @brief Get public account recommend level type.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account recommend level type, @see @ref MtcPaConstants::EN_MTC_PA_RECMD_LV_UNKNOWN.
 */
  public static int Mtc_PaDetailGetRecmdLv(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetRecmdLv(iSessId);
  }

/**
 * @brief Get public account id type.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account id type, @see @ref MtcPaConstants::EN_MTC_PA_ID_UNKNOWN.
 */
  public static int Mtc_PaDetailGetIdType(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetIdType(iSessId);
  }

/**
 * @brief Get public account menu type.
 *
 * @param [in] iSessId The session id.
 *
 * @return 1 when public account have menu setting, otherwise return 0.
 */
  public static int Mtc_PaDetailGetMenuType(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetMenuType(iSessId);
  }

/**
 * @brief The public account subscribe status.
 *
 * @param [in] iSessId The session id.
 *
 * @return 1 when public account have subscribed, otherwise return 0.
 */
  public static int Mtc_PaDetailGetSubsStat(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetSubsStat(iSessId);
  }

/**
 * @brief The public account accept satus.
 *
 * @param [in] iSessId The session id.
 *
 * @return 1 when client accept public account pushed, otherwise return 0.
 */
  public static int Mtc_PaDetailGetAcptStat(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetAcptStat(iSessId);
  }

/**
 * @brief The public account active satus.
 *
 * @param [in] iSessId The session id.
 *
 * @retval 0 Indicates public account is active status, 
 * @retval 1 Indicates public account is paused status.
 * @retval 2 Indicates public account is closed status.
 */
  public static int Mtc_PaDetailGetActiveStat(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetActiveStat(iSessId);
  }

/**
 * @brief The public account tel.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account tel.
 */
  public static String Mtc_PaDetailGetTel(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetTel(iSessId);
  }

/**
 * @brief The public account email.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account email.
 */
  public static String Mtc_PaDetailGetEmail(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetEmail(iSessId);
  }

/**
 * @brief The public account zip.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account zip.
 */
  public static String Mtc_PaDetailGetZip(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetZip(iSessId);
  }

/**
 * @brief The public account address.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account address.
 */
  public static String Mtc_PaDetailGetAddr(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetAddr(iSessId);
  }

/**
 * @brief The public account field.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account field.
 */
  public static String Mtc_PaDetailGetField(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetField(iSessId);
  }

/**
 * @brief Get public account logo url.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account logo url.
 */
  public static String Mtc_PaDetailGetLogoUrl(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetLogoUrl(iSessId);
  }

/**
 * @brief Get public account qrcode.
 *
 * @param [in] iSessId The session id.
 *
 * @return The public account qrcode.
 */
  public static String Mtc_PaDetailGetQrCode(int iSessId) {
    return MtcPaJNI.Mtc_PaDetailGetQrCode(iSessId);
  }

/**
 * @brief Get public account menu command id.
 *
 * @param [in] iMenuId The menu id.
 *
 * @return The public account menu command id.
 */
  public static String Mtc_PaMenuGetCmdId(int iMenuId) {
    return MtcPaJNI.Mtc_PaMenuGetCmdId(iMenuId);
  }

/**
 * @brief Get public account menu command type.
 *
 * @param [in] iMenuId The menu id.
 *
 * @return The public account menu command type, @see @ref MtcPaConstants::EN_MTC_PA_MENU_CMD_SMLT_MSG.
 */
  public static int Mtc_PaMenuGetCmdType(int iMenuId) {
    return MtcPaJNI.Mtc_PaMenuGetCmdType(iMenuId);
  }

/**
 * @brief Get public account menu title.
 *
 * @param [in] iMenuId The menu id.
 *
 * @return The public account menu title.
 */
  public static String Mtc_PaMenuGetTitle(int iMenuId) {
    return MtcPaJNI.Mtc_PaMenuGetTitle(iMenuId);
  }

/**
 * @brief Get public account menu priority.
 *
 * @param [in] iMenuId The menu id.
 *
 * @return The public account menu priority.
 */
  public static int Mtc_PaMenuGetPriority(int iMenuId) {
    return MtcPaJNI.Mtc_PaMenuGetPriority(iMenuId);
  }

/**
 * @brief Get public account submenu size.
 *
 * @param [in] iMenuId The menu id.
 *
 * @return The public account submenu size.
 */
  public static int Mtc_PaMenuGetSubmenuSize(int iMenuId) {
    return MtcPaJNI.Mtc_PaMenuGetSubmenuSize(iMenuId);
  }

/**
 * @brief Get public account submenu size.
 *
 * @param [in] iMenuId The menu id.
 * @param [in] iIndex The submenu index.
 *
 * @return The public account submenu id successfully, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaMenuGetSubmenuId(int iMenuId, int iIndex) {
    return MtcPaJNI.Mtc_PaMenuGetSubmenuId(iMenuId, iIndex);
  }

/**
 * @brief Get public account message media type.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account message media type, @see @ref MtcPaConstants::EN_MTC_PA_MEDIA_UNKNOWN.
 */
  public static int Mtc_PaMsgGetMediaType(int iMsgId) {
    return MtcPaJNI.Mtc_PaMsgGetMediaType(iMsgId);
  }

/**
 * @brief Get public account message unique id.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account message unique id.
 */
  public static String Mtc_PaMsgGetMsgUuid(int iMsgId) {
    return MtcPaJNI.Mtc_PaMsgGetMsgUuid(iMsgId);
  }

/**
 * @brief Get public account unique id.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account unique id.
 */
  public static String Mtc_PaMsgGetPaUuid(int iMsgId) {
    return MtcPaJNI.Mtc_PaMsgGetPaUuid(iMsgId);
  }

/**
 * @brief Get public account short message digest.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account short message digest.
 */
  public static String Mtc_PaMsgGetSmsDigest(int iMsgId) {
    return MtcPaJNI.Mtc_PaMsgGetSmsDigest(iMsgId);
  }

/**
 * @brief Get public account text message.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account text message.
 */
  public static String Mtc_PaMsgGetText(int iMsgId) {
    return MtcPaJNI.Mtc_PaMsgGetText(iMsgId);
  }

/**
 * @brief Get public account message create time.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account message create time.
 */
  public static int Mtc_PaMsgGetCreateTime(int iMsgId) {
    return MtcPaJNI.Mtc_PaMsgGetCreateTime(iMsgId);
  }

/**
 * @brief Get public account message active status.
 *
 * @param [in] iMsgId The message id.
 *
 * @retval 0 Indicates public account is active status, 
 * @retval 1 Indicates public account is paused status.
 * @retval 2 Indicates public account is closed status.
 */
  public static int Mtc_PaMsgGetActiveStat(int iMsgId) {
    return MtcPaJNI.Mtc_PaMsgGetActiveStat(iMsgId);
  }

/**
 * @brief Get public account message forwordable.
 *
 * @param [in] iMsgId The message id.
 *
 * @return 0 when message is forwordable, otherwise return 1.
 */
  public static int Mtc_PaMsgGetFwdable(int iMsgId) {
    return MtcPaJNI.Mtc_PaMsgGetFwdable(iMsgId);
  }

/**
 * @brief Get public account geolocation information id.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account geolocation information id on succeed, otherwise return ZMAXUINT.
 */
  public static int Mtc_PaMsgGetGInfoId(int iMsgId) {
    return MtcPaJNI.Mtc_PaMsgGetGInfoId(iMsgId);
  }

/**
 * @brief Get public account article message size.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account article message size.
 */
  public static int Mtc_PaMsgGetArtMsgSize(int iMsgId) {
    return MtcPaJNI.Mtc_PaMsgGetArtMsgSize(iMsgId);
  }

/**
 * @brief Get public account article message size.
 *
 * @param [in] iMsgId The message id.
 *
 * @return Thepublic account article message id.
 */
  public static int Mtc_PaMsgGetArtMsgId(int iMsgId, int iIndex) {
    return MtcPaJNI.Mtc_PaMsgGetArtMsgId(iMsgId, iIndex);
  }

/**
 * @brief Get public account article message title.
 *
 * @param [in] iArtMsgId The article message id.
 *
 * @return The public account article message title.
 */
  public static String Mtc_PaArtMsgGetTitle(int iArtMsgId) {
    return MtcPaJNI.Mtc_PaArtMsgGetTitle(iArtMsgId);
  }

/**
 * @brief Get public account article message author.
 *
 * @param [in] iArtMsgId The article message id.
 *
 * @return The public account article message author.
 */
  public static String Mtc_PaArtMsgGetAuthor(int iArtMsgId) {
    return MtcPaJNI.Mtc_PaArtMsgGetAuthor(iArtMsgId);
  }

/**
 * @brief Get public account article message thumb link.
 *
 * @param [in] iArtMsgId The article message id.
 *
 * @return The public account article message thumb link.
 */
  public static String Mtc_PaArtMsgGetThumbLink(int iArtMsgId) {
    return MtcPaJNI.Mtc_PaArtMsgGetThumbLink(iArtMsgId);
  }

/**
 * @brief Get public account article message original link.
 *
 * @param [in] iArtMsgId The article message id.
 *
 * @return The public account article message original link.
 */
  public static String Mtc_PaArtMsgGetOrigLink(int iArtMsgId) {
    return MtcPaJNI.Mtc_PaArtMsgGetOrigLink(iArtMsgId);
  }

/**
 * @brief Get public account article message body link.
 *
 * @param [in] iArtMsgId The article message id.
 *
 * @return The public account article message body link.
 */
  public static String Mtc_PaArtMsgGetBodyLink(int iArtMsgId) {
    return MtcPaJNI.Mtc_PaArtMsgGetBodyLink(iArtMsgId);
  }

/**
 * @brief Get public account article message source link.
 *
 * @param [in] iArtMsgId The article message id.
 *
 * @return The public account article message source link.
 */
  public static String Mtc_PaArtMsgGetSrcLink(int iArtMsgId) {
    return MtcPaJNI.Mtc_PaArtMsgGetSrcLink(iArtMsgId);
  }

/**
 * @brief Get public account article message main text.
 *
 * @param [in] iArtMsgId The article message id.
 *
 * @return The public account article message main text.
 */
  public static String Mtc_PaArtMsgGetMainText(int iArtMsgId) {
    return MtcPaJNI.Mtc_PaArtMsgGetMainText(iArtMsgId);
  }

/**
 * @brief Get public account article message media unique id.
 *
 * @param [in] iArtMsgId The article message id.
 *
 * @return The public account article message media unique id.
 */
  public static String Mtc_PaArtMsgGetMediaUuid(int iArtMsgId) {
    return MtcPaJNI.Mtc_PaArtMsgGetMediaUuid(iArtMsgId);
  }

/**
 * @brief Get public account basic message title.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account basic message title.
 */
  public static String Mtc_PaBscMsgGetTitle(int iMsgId) {
    return MtcPaJNI.Mtc_PaBscMsgGetTitle(iMsgId);
  }

/**
 * @brief Get public account basic message file size.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account basic message file size.
 */
  public static int Mtc_PaBscMsgGetFileSize(int iMsgId) {
    return MtcPaJNI.Mtc_PaBscMsgGetFileSize(iMsgId);
  }

/**
 * @brief Get public account basic message file type.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account basic message file type.
 */
  public static String Mtc_PaBscMsgGetFileType(int iMsgId) {
    return MtcPaJNI.Mtc_PaBscMsgGetFileType(iMsgId);
  }

/**
 * @brief Get public account basic message file duration.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account basic message file duration.
 */
  public static int Mtc_PaBscMsgGetFileDuration(int iMsgId) {
    return MtcPaJNI.Mtc_PaBscMsgGetFileDuration(iMsgId);
  }

/**
 * @brief Get public account basic message thumb link.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account basic message thumb link.
 */
  public static String Mtc_PaBscMsgGetThumbLink(int iMsgId) {
    return MtcPaJNI.Mtc_PaBscMsgGetThumbLink(iMsgId);
  }

/**
 * @brief Get public account basic message original link.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account basic message original link.
 */
  public static String Mtc_PaBscMsgGetOrigLink(int iMsgId) {
    return MtcPaJNI.Mtc_PaBscMsgGetOrigLink(iMsgId);
  }

/**
 * @brief Get public account basic message media unique id.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account basic message media unique id.
 */
  public static String Mtc_PaBscMsgGetMediaUuid(int iMsgId) {
    return MtcPaJNI.Mtc_PaBscMsgGetMediaUuid(iMsgId);
  }

/**
 * @brief Get public account basic message create time.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account basic message create time.
 */
  public static int Mtc_PaBscMsgGetCreateTime(int iMsgId) {
    return MtcPaJNI.Mtc_PaBscMsgGetCreateTime(iMsgId);
  }

/**
 * @brief Get public account card message title.
 *
 * @param [in] iMsgId The card message id.
 *
 * @return The public account card message title.
 */
  public static String Mtc_PaCardMsgGetTitle(int iMsgId) {
    return MtcPaJNI.Mtc_PaCardMsgGetTitle(iMsgId);
  }

/**
 * @brief Get public account card message author.
 *
 * @param [in] iMsgId The card message id.
 *
 * @return The public account card message author.
 */
  public static String Mtc_PaCardMsgGetAuthor(int iMsgId) {
    return MtcPaJNI.Mtc_PaCardMsgGetAuthor(iMsgId);
  }

/**
 * @brief Get public account card message thumb link.
 *
 * @param [in] iMsgId The card message id.
 *
 * @return The public account card message thumb link.
 */
  public static String Mtc_PaCardMsgGetThumbLink(int iMsgId) {
    return MtcPaJNI.Mtc_PaCardMsgGetThumbLink(iMsgId);
  }

/**
 * @brief Get public account card message original link.
 *
 * @param [in] iMsgId The card message id.
 *
 * @return The public account card message original link.
 */
  public static String Mtc_PaCardMsgGetOrigLink(int iMsgId) {
    return MtcPaJNI.Mtc_PaCardMsgGetOrigLink(iMsgId);
  }

/**
 * @brief Get public account card message body link.
 *
 * @param [in] iMsgId The card message id.
 *
 * @return The public account card message body link.
 */
  public static String Mtc_PaCardMsgGetBodyLink(int iMsgId) {
    return MtcPaJNI.Mtc_PaCardMsgGetBodyLink(iMsgId);
  }

/**
 * @brief Get public account card message source link.
 *
 * @param [in] iMsgId The card message id.
 *
 * @return The public account card message source link.
 */
  public static String Mtc_PaCardMsgGetSrcLink(int iMsgId) {
    return MtcPaJNI.Mtc_PaCardMsgGetSrcLink(iMsgId);
  }

/**
 * @brief Get public account card message main text.
 *
 * @param [in] iMsgId The card message id.
 *
 * @return The public account card message main text.
 */
  public static String Mtc_PaCardMsgGetMainText(int iMsgId) {
    return MtcPaJNI.Mtc_PaCardMsgGetMainText(iMsgId);
  }

/**
 * @brief Get public account card message media unique id.
 *
 * @param [in] iMsgId The card message id.
 *
 * @return The public account card message media unique id.
 */
  public static String Mtc_PaCardMsgGetMediaUuid(int iMsgId) {
    return MtcPaJNI.Mtc_PaCardMsgGetMediaUuid(iMsgId);
  }

/**
 * @brief Get public account template message top color.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message top color, @see @ref MtcPaConstants::EN_MTC_PA_COLOR_UNKNOWN.
 */
  public static int Mtc_PaTmplMsgGetTopColor(int iMsgId) {
    return MtcPaJNI.Mtc_PaTmplMsgGetTopColor(iMsgId);
  }

/**
 * @brief Get public account template message title.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message title.
 */
  public static String Mtc_PaTmplMsgGetTitle(int iMsgId) {
    return MtcPaJNI.Mtc_PaTmplMsgGetTitle(iMsgId);
  }

/**
 * @brief Get public account template message first text.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message first text.
 */
  public static String Mtc_PaTmplMsgGetFirstText(int iMsgId) {
    return MtcPaJNI.Mtc_PaTmplMsgGetFirstText(iMsgId);
  }

/**
 * @brief Get public account template message first color.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message first color, @see @ref MtcPaConstants::EN_MTC_PA_COLOR_UNKNOWN.
 */
  public static int Mtc_PaTmplMsgGetFirstColor(int iMsgId) {
    return MtcPaJNI.Mtc_PaTmplMsgGetFirstColor(iMsgId);
  }

/**
 * @brief Get public account template message last text.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message last text.
 */
  public static String Mtc_PaTmplMsgGetLastText(int iMsgId) {
    return MtcPaJNI.Mtc_PaTmplMsgGetLastText(iMsgId);
  }

/**
 * @brief Get public account template message last color.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message last color, @see @ref MtcPaConstants::EN_MTC_PA_COLOR_UNKNOWN.
 */
  public static int Mtc_PaTmplMsgGetLastColor(int iMsgId) {
    return MtcPaJNI.Mtc_PaTmplMsgGetLastColor(iMsgId);
  }

/**
 * @brief Get public account template message url.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message url.
 */
  public static String Mtc_PaTmplMsgGetUrl(int iMsgId) {
    return MtcPaJNI.Mtc_PaTmplMsgGetUrl(iMsgId);
  }

/**
 * @brief Get public account template message key note size.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message key note size.
 */
  public static int Mtc_PaTmplMsgGetKeyNoteSize(int iMsgId) {
    return MtcPaJNI.Mtc_PaTmplMsgGetKeyNoteSize(iMsgId);
  }

/**
 * @brief Get public account template message key note size.
 *
 * @param [in] iMsgId The message id.
 *
 * @return Thepublic account template message key note id.
 */
  public static int Mtc_PaTmplMsgGetKeyNoteId(int iMsgId, int iIndex) {
    return MtcPaJNI.Mtc_PaTmplMsgGetKeyNoteId(iMsgId, iIndex);
  }

/**
 * @brief Get public account template message key note name.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message key note name.
 */
  public static String Mtc_PaKeyNoteGetName(int iNoteId) {
    return MtcPaJNI.Mtc_PaKeyNoteGetName(iNoteId);
  }

/**
 * @brief Get public account template message key note value text.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message key note value text.
 */
  public static String Mtc_PaKeyNoteGetValueText(int iNoteId) {
    return MtcPaJNI.Mtc_PaKeyNoteGetValueText(iNoteId);
  }

/**
 * @brief Get public account template message key note value color.
 *
 * @param [in] iMsgId The message id.
 *
 * @return The public account template message key note value color, @see @ref MtcPaConstants::EN_MTC_PA_COLOR_UNKNOWN.
 */
  public static int Mtc_PaKeyNoteGetValueColor(int iNoteId) {
    return MtcPaJNI.Mtc_PaKeyNoteGetValueColor(iNoteId);
  }

}
