/**
 * @file MtcProfDb.java
 * @brief MtcProfDb interface
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

/**
 * @brief MtcProfDb interface
 */
public class MtcProfDb {
/**
 * @brief Get application version from database.
 *
 * @return Application version.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetAppVer
 */
  public static String Mtc_ProfDbGetAppVer() {
    return MtcProfDbJNI.Mtc_ProfDbGetAppVer();
  }

/**
 * @brief Set application version from database.
 *
 * @param [in] pcAppVer The application version.
 *
 * @retval MtcCommonConstants::ZOK Set application version successfully.
 * @retval MtcCommonConstants::ZFAILED Set application version failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetAppVer
 */
  public static int Mtc_ProfDbSetAppVer(String pcAppVer) {
    return MtcProfDbJNI.Mtc_ProfDbSetAppVer(pcAppVer);
  }

/**
 * @brief Get remember password option from database.
 *
 * @retval true Remember password.
 * @retval false Do not remember password.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetRemPwd
 */
  public static boolean Mtc_ProfDbGetRemPwd() {
    return MtcProfDbJNI.Mtc_ProfDbGetRemPwd();
  }

/**
 * @brief Set remember password option.
 *
 * @param [in] bRember The option of remembering password.
 *
 * @retval MtcCommonConstants::ZOK Set remember password option successfully.
 * @retval MtcCommonConstants::ZFAILED Set remember password option failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetRemPwd
 */
  public static int Mtc_ProfDbSetRemPwd(boolean bRember) {
    return MtcProfDbJNI.Mtc_ProfDbSetRemPwd(bRember);
  }

/**
 * @brief Get the user automatically login option from database.
 *
 * @retval true User will automatically login.
 * @retval false User will not automatically login.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetAutoLogin
*/
  public static boolean Mtc_ProfDbGetAutoLogin() {
    return MtcProfDbJNI.Mtc_ProfDbGetAutoLogin();
  }

/**
 * @brief Set the user automatically login option.
 *
 * @param [in] bAuto User automatically login option.
 *
 * @retval MtcCommonConstants::ZOK Set the option successfully.
 * @retval MtcCommonConstants::ZFAILED Set the option option failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetAutoLogin
 */
  public static int Mtc_ProfDbSetAutoLogin(boolean bAuto) {
    return MtcProfDbJNI.Mtc_ProfDbSetAutoLogin(bAuto);
  }

/**
 * @brief Get avatar file name.
 *
 * @return The string of avatar file name.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetAvatarFile
 */
  public static String Mtc_ProfDbGetAvatarFile() {
    return MtcProfDbJNI.Mtc_ProfDbGetAvatarFile();
  }

/**
 * @brief Set avatar file name.
 *
 * @param [in] pcFileName Avatar file name.
 *
 * @retval MtcCommonConstants::ZOK Set avatar file name successfully.
 * @retval MtcCommonConstants::ZFAILED Set avatar file name failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetAvatarFile
 */
  public static int Mtc_ProfDbSetAvatarFile(String pcFileName) {
    return MtcProfDbJNI.Mtc_ProfDbSetAvatarFile(pcFileName);
  }

/**
 * @brief Get country code.
 *
 * @return The string of country code.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetCountryCode
 */
  public static String Mtc_ProfDbGetCountryCode() {
    return MtcProfDbJNI.Mtc_ProfDbGetCountryCode();
  }

/**
 * @brief Set country code.
 *
 * @param [in] pcCountryCode Country code.
 *
 * @retval MtcCommonConstants::ZOK Set country code successfully.
 * @retval MtcCommonConstants::ZFAILED Set country code failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetCountryCode
 */
  public static int Mtc_ProfDbSetCountryCode(String pcCountryCode) {
    return MtcProfDbJNI.Mtc_ProfDbSetCountryCode(pcCountryCode);
  }

/**
 * @brief Get area code.
 *
 * @return The string of area code.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetAreaCode
 */
  public static String Mtc_ProfDbGetAreaCode() {
    return MtcProfDbJNI.Mtc_ProfDbGetAreaCode();
  }

/**
 * @brief Set area code.
 *
 * @param [in] pcAreaCode Country code.
 *
 * @retval MtcCommonConstants::ZOK Set area code successfully.
 * @retval MtcCommonConstants::ZFAILED Set area code failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetAreaCode
 */
  public static int Mtc_ProfDbSetAreaCode(String pcAreaCode) {
    return MtcProfDbJNI.Mtc_ProfDbSetAreaCode(pcAreaCode);
  }

/**
 * @brief Get the client provisioning enable from database.
 *
 * @retval true Start client provisioning.
 * @retval false Do not start client provisioning.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetCpEnable
*/
  public static boolean Mtc_ProfDbGetCpEnable() {
    return MtcProfDbJNI.Mtc_ProfDbGetCpEnable();
  }

/**
 * @brief Set client provisioning enable.
 *
 * @param [in] bCpEnable The client provisioning option.
 *
 * @retval MtcCommonConstants::ZOK Set the client provisioning option successfully.
 * @retval MtcCommonConstants::ZFAILED Set the client provisioning option failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetCpEnable
 */
  public static int Mtc_ProfDbSetCpEnable(boolean bCpEnable) {
    return MtcProfDbJNI.Mtc_ProfDbSetCpEnable(bCpEnable);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [out] ppcParm The parameter value.
 *
 * @retval MtcCommonConstants::ZOK get extension parameter successfully.
 * @retval MtcCommonConstants::ZFAILED get extension parameter failed, 
 *                 the extension parameter is not exist.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetExtnParm
 */
  public static int Mtc_ProfDbGetExtnParm(String pcName, MtcString ppcParm) {
    return MtcProfDbJNI.Mtc_ProfDbGetExtnParm(pcName, ppcParm);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [out] pbParm The parameter value.
 *
 * @retval MtcCommonConstants::ZOK get extension parameter successfully.
 * @retval MtcCommonConstants::ZFAILED get extension parameter failed, 
 *                 the extension parameter is not exist.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetExtnParm
 */
  public static int Mtc_ProfDbGetExtnParmBool(String pcName, MtcNumber pbParm) {
    return MtcProfDbJNI.Mtc_ProfDbGetExtnParmBool(pcName, pbParm);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [out] piParm The parameter value.
 *
 * @retval MtcCommonConstants::ZOK get extension parameter successfully.
 * @retval MtcCommonConstants::ZFAILED get extension parameter failed, 
 *                 the extension parameter is not exist.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetExtnParm
 */
  public static int Mtc_ProfDbGetExtnParmInt(String pcName, MtcNumber piParm) {
    return MtcProfDbJNI.Mtc_ProfDbGetExtnParmInt(pcName, piParm);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [out] piParm The parameter value.
 *
 * @retval MtcCommonConstants::ZOK get extension parameter successfully.
 * @retval MtcCommonConstants::ZFAILED get extension parameter failed, 
 *                 the extension parameter is not exist.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetExtnParm
 */
  public static int Mtc_ProfDbGetExtnParmUint(String pcName, MtcNumber piParm) {
    return MtcProfDbJNI.Mtc_ProfDbGetExtnParmUint(pcName, piParm);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] iIndex The parameter index.
 *
 * @return The parameter value when get extension parameter successfully, 
 *              otherwise return empty string.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetExtnParm
 */
  public static String Mtc_ProfDbGetExtnParmX(String pcName, int iIndex) {
    return MtcProfDbJNI.Mtc_ProfDbGetExtnParmX(pcName, iIndex);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 *
 * @retval MtcCommonConstants::ZOK Get the parameter count successfully.
 * @retval MtcCommonConstants::ZFAILED Get the parameter count failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetExtnParm
 */
  public static int Mtc_ProfDbGetExtnParmCount(String pcName) {
    return MtcProfDbJNI.Mtc_ProfDbGetExtnParmCount(pcName);
  }

/**
 * @brief Set extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] pcVal The parameter value.
 *
 * @retval MtcCommonConstants::ZOK Set the parameter successfully.
 * @retval MtcCommonConstants::ZFAILED Set the parameter failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetExtnParm
 */
  public static int Mtc_ProfDbSetExtnParm(String pcName, String pcVal) {
    return MtcProfDbJNI.Mtc_ProfDbSetExtnParm(pcName, pcVal);
  }

/**
 * @brief Set extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] bVal The parameter value.
 *
 * @retval MtcCommonConstants::ZOK Set the parameter successfully.
 * @retval MtcCommonConstants::ZFAILED Set the parameter failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetExtnParm
 */
  public static int Mtc_ProfDbSetExtnParmBool(String pcName, boolean bVal) {
    return MtcProfDbJNI.Mtc_ProfDbSetExtnParmBool(pcName, bVal);
  }

/**
 * @brief Set extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] iVal The parameter value.
 *
 * @retval MtcCommonConstants::ZOK Set the parameter successfully.
 * @retval MtcCommonConstants::ZFAILED Set the parameter failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetExtnParm
 */
  public static int Mtc_ProfDbSetExtnParmInt(String pcName, int iVal) {
    return MtcProfDbJNI.Mtc_ProfDbSetExtnParmInt(pcName, iVal);
  }

/**
 * @brief Set extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] iVal The parameter value.
 *
 * @retval MtcCommonConstants::ZOK Set the parameter successfully.
 * @retval MtcCommonConstants::ZFAILED Set the parameter failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetExtnParm
 */
  public static int Mtc_ProfDbSetExtnParmUint(String pcName, int iVal) {
    return MtcProfDbJNI.Mtc_ProfDbSetExtnParmUint(pcName, iVal);
  }

/**
 * @brief Add extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] pcVal The parameter value.
 *
 * @retval MtcCommonConstants::ZOK Add the parameter successfully.
 * @retval MtcCommonConstants::ZFAILED Add the parameter failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetExtnParm
 */
  public static int Mtc_ProfDbAddExtnParm(String pcName, String pcVal) {
    return MtcProfDbJNI.Mtc_ProfDbAddExtnParm(pcName, pcVal);
  }

/**
 * @brief Add extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] wNameLen The parameter name length.
 * @param [in] pcVal The parameter value.
 * @param [in] wValLen The parameter value length.
 *
 * @retval MtcCommonConstants::ZOK Add the parameter successfully.
 * @retval MtcCommonConstants::ZFAILED Add the parameter failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetExtnParm
 */
  public static int Mtc_ProfDbAddExtnParmN(String pcName, int wNameLen, String pcVal, int wValLen) {
    return MtcProfDbJNI.Mtc_ProfDbAddExtnParmN(pcName, wNameLen, pcVal, wValLen);
  }

}
