/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

public class SWIGTYPE_p_MTC_ACT {
  private long swigCPtr;

  protected SWIGTYPE_p_MTC_ACT(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_MTC_ACT() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_MTC_ACT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

